apiVersion: apps/v1
kind: Deployment
metadata:
  name: reconstruction-postgres
  namespace: reconstruction-db
  labels:
    app: reconstruction-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reconstruction-postgres
  template:
    metadata:
      labels:
        app: reconstruction-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: reconstruction-postgres-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: reconstruction-postgres-pvc
