apiVersion: v1
kind: Secret
metadata:
  name: reconstruction-postgres-secret
  namespace: reconstruction-db
type: Opaque
stringData:
  POSTGRES_USER: "reconstruction_user"
  POSTGRES_PASSWORD: "strylq4IK1ooqtaAB1PrmtODhx0B9c9BPOAV9gdKdiE="
  POSTGRES_DB: "reconstruction_db"
