apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-bot
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/immaribeiro/homelab.git
    targetRevision: main
    path: k8s/manifests
    directory:
      include: homelab-bot.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: homelab-bot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
