apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reconstruction-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/immaribeiro/homelab.git
    targetRevision: HEAD
    path: k8s/manifests/reconstruction-db
  destination:
    server: https://kubernetes.default.svc
    namespace: reconstruction-db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
