apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-immas-org
  namespace: cert-manager
spec:
  secretName: wildcard-immas-org-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.immas.org"
  dnsNames:
    - "*.immas.org"
    - "immas.org"
