apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home
  annotations: {}
spec:
  ingressClassName: nginx
  rules:
  - host: home.immas.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: home-nginx
            port:
              number: 80
