# Sample inventory generated for testing (Terraform normally generates this)
all:
  children:
    control_plane:
      hosts:
        192.168.100.11:
    workers:
      hosts:
        192.168.100.12:
        192.168.100.13:
  vars:
    ansible_user: "ubuntu"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_python_interpreter: /usr/bin/python3
