all:
  children:
    control_plane:
      hosts:
        k3s-control-1:
          ansible_host: 127.0.0.1
          ansible_port: 62465
          node_ip: 192.168.105.2
    workers:
      hosts:
        k3s-worker-1:
          ansible_host: 127.0.0.1
          ansible_port: 60597
          node_ip: 192.168.105.3
        k3s-worker-2:
          ansible_host: 127.0.0.1
          ansible_port: 60630
          node_ip: 192.168.105.4
  vars:
    ansible_user: "ubuntu"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_python_interpreter: /usr/bin/python3
